version: "2"
services:
  databases:
    image: mysql/mysql-server
    ports:
      - "81:81"
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=test
  service:
    image: my-app
    ports:
      - "80:80"